telegram:
    api_id: 35195904
    api_hash: c16765efa37272998e93921b065d8c88
    phone: +1 980 516 8553
vk:
    app_id: 0
    access_token: ""
    enabled: false
api:
    port: "8081"
collector_interval: 10s
